#!/bin/bash

if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

if [ -z "$(pgrep system-config-printer-applet)" ] ; then
    system-config-printer-applet &
fi

if [ -z "$(pgrep synapse)" ] ; then
    synapse -s &
fi

