#!/bin/bash
# 

rm -f ~/.xmonad/xmonad.state

export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

xrdb -merge .Xdefaults

xcompmgr -n &

gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

setxkbmap -option 'ctrl:nocaps'

xsetroot -cursor_name left_ptr

stalonetray -c ~/.xmonad/stalonetrayrc --slot-size 23 &

echo 200 | sudo tee /sys/devices/platform/i8042/serio1/serio2/sensitivity &

feh --bg-scale /home/boni/Pictures/background.png &

eval "$(ssh-agent)" &
ssh-add &
keychain &

#google-drive-ocamlfuse /home/boni/googledrive &

redshift &

google-chrome-stable &
nautilus &
subl &
dropbox start &
slack &

# Now, finally, start xmonad
exec xmonad

